# see R files used in GKTfunctions
# install at root in R
install.packages('caTools', repos = 'http://cran.cnr.berkeley.edu/',  lib='/usr/local/lib/R/3.3/site-library')
install.packages('MuMIn', repos = 'http://cran.cnr.berkeley.edu/',  lib='/usr/local/lib/R/3.3/site-library')
install.packages('pROC', repos = 'http://cran.cnr.berkeley.edu/',  lib='/usr/local/lib/R/3.3/site-library')
install.packages('caret', repos = 'http://cran.cnr.berkeley.edu/',  lib='/usr/local/lib/R/3.3/site-library')
#install.packages('rms', repos = 'http://cran.cnr.berkeley.edu/',  lib='/usr/local/lib/R/3.3/site-library')
install.packages('pscl', repos = 'http://cran.cnr.berkeley.edu/',  lib='/usr/local/lib/R/3.3/site-library')
install.packages('games', repos = 'http://cran.cnr.berkeley.edu/',  lib='/usr/local/lib/R/3.3/site-library')
install.packages('optimx', repos = 'http://cran.cnr.berkeley.edu/',  lib='/usr/local/lib/R/3.3/site-library')
install.packages('Rcgmin', repos = 'http://cran.cnr.berkeley.edu/',  lib='/usr/local/lib/R/3.3/site-library')
install.packages('BB', repos = 'http://cran.cnr.berkeley.edu/',  lib='/usr/local/lib/R/3.3/site-library')
install.packages('nloptr', repos = 'http://cran.cnr.berkeley.edu/',  lib='/usr/local/lib/R/3.3/site-library')
install.packages('lme4', repos = 'http://cran.cnr.berkeley.edu/',  lib='/usr/local/lib/R/3.3/site-library')
install.packages('RColorBrewer', repos = 'http://cran.cnr.berkeley.edu/',  lib='/usr/local/lib/R/3.3/site-library')
#install.packages('erer', repos = 'http://cran.cnr.berkeley.edu/',  lib='/usr/local/lib/R/3.3/site-library')
install.packages('XML', repos = 'http://cran.cnr.berkeley.edu/',  lib='/usr/local/lib/R/3.3/site-library')
