[section_engine]
MODEL = gpt-3.5-turbo-instruct
MAX_TOKENS = 300
TEMPERATURE = 0
# Sets a maximum index for responses to run. Useful to specify how many responses we want to run on (partial execution). Set to -1 to run them all.
RUN_UP_TO = 500
