status = warn

appender.R.type = RollingFile
appender.R.name = R
appender.R.fileName = WorkflowComponent.log
appender.R.filePattern = WorkflowComponent.log.%i
appender.R.layout.type = PatternLayout
appender.R.layout.pattern = %p: [%t] %c %d{dd MMM yyyy HH:mm:ss,SSS} - %m%n
appender.R.policies.type = Policies
appender.R.policies.size.type = SizeBasedTriggeringPolicy
appender.R.policies.size.size = 1000MB
appender.R.strategy.type = DefaultRolloverStrategy
appender.R.strategy.max = 10

appender.stdout.type = Console
appender.stdout.name = stdout
appender.stdout.layout.type = PatternLayout
appender.stdout.layout.pattern = %p: [%t] %c %d{dd MMM yyyy HH:mm:ss,SSS} - %m%n

logger.pslclearnsphere.name = edu.cmu.pslc.learnsphere
logger.pslclearnsphere.level = debug

rootLogger.level = debug
rootLogger.appenderRef.R.ref = R
